-- MySQL Script generated by MySQL Workbench
-- Wed Sep  8 18:26:45 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rpg
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rpg
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rpg` DEFAULT CHARACTER SET utf8 ;
USE `rpg` ;

-- -----------------------------------------------------
-- Table `rpg`.`player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rpg`.`player` (
  `id_player` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `gold` INT NULL,
  PRIMARY KEY (`id_player`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rpg`.`classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rpg`.`classes` (
  `id_classe` INT NOT NULL AUTO_INCREMENT,
  `nm_classe` VARCHAR(45) NULL,
  PRIMARY KEY (`id_classe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rpg`.`personagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rpg`.`personagens` (
  `id_personagem` INT NOT NULL AUTO_INCREMENT,
  `nick` VARCHAR(45) NULL,
  `xp` INT NULL DEFAULT 0,
  `xp_max` INT NULL DEFAULT 100,
  `lv` INT NULL,
  `id_classe` INT NOT NULL,
  `id_player` INT NOT NULL,
  PRIMARY KEY (`id_personagem`),
  INDEX `fk_personagens_classes1_idx` (`id_classe` ASC) ,
  INDEX `fk_personagens_player1_idx` (`id_player` ASC) ,
  CONSTRAINT `fk_personagens_classes1`
    FOREIGN KEY (`id_classe`)
    REFERENCES `rpg`.`classes` (`id_classe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personagens_player1`
    FOREIGN KEY (`id_player`)
    REFERENCES `rpg`.`player` (`id_player`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rpg`.`inimigos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rpg`.`inimigos` (
  `id_inimigo` INT NOT NULL AUTO_INCREMENT,
  `nm_inimigo` VARCHAR(45) NULL,
  `classe` INT NULL,
  `xp` INT NULL,
  `lv` INT NULL,
  `raridade` INT NULL,
  `drop` INT NULL,
  PRIMARY KEY (`id_inimigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rpg`.`skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rpg`.`skills` (
  `id_skill` INT NOT NULL,
  `nm_skill` VARCHAR(45) NULL,
  `lv` INT NULL,
  `mutiplicador` INT NULL,
  `id_classe` INT NOT NULL,
  PRIMARY KEY (`id_skill`),
  INDEX `fk_skills_classes1_idx` (`id_classe` ASC) ,
  CONSTRAINT `fk_skills_classes1`
    FOREIGN KEY (`id_classe`)
    REFERENCES `rpg`.`classes` (`id_classe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rpg`.`Itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rpg`.`Itens` (
  `id_item` INT NOT NULL,
  `nm_item` VARCHAR(45) NULL,
  `lv` VARCHAR(45) NULL,
  `valor` VARCHAR(45) NULL,
  PRIMARY KEY (`id_item`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rpg`.`atributos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rpg`.`atributos` (
  `id_atributo` INT NOT NULL AUTO_INCREMENT,
  `sta` INT NULL,
  `str` INT NULL,
  `int` INT NULL,
  `dex` INT NULL,
  `id_classe` INT NULL,
  `id_inimigo` INT NULL,
  `id_item` INT NULL,
  PRIMARY KEY (`id_atributo`),
  INDEX `fk_atributos_classes1_idx` (`id_classe` ASC) ,
  INDEX `fk_atributos_inimigos1_idx` (`id_inimigo` ASC) ,
  INDEX `fk_atributos_Itens1_idx` (`id_item` ASC) ,
  CONSTRAINT `fk_atributos_classes1`
    FOREIGN KEY (`id_classe`)
    REFERENCES `rpg`.`classes` (`id_classe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atributos_inimigos1`
    FOREIGN KEY (`id_inimigo`)
    REFERENCES `rpg`.`inimigos` (`id_inimigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atributos_Itens1`
    FOREIGN KEY (`id_item`)
    REFERENCES `rpg`.`Itens` (`id_item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rpg`.`raridades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rpg`.`raridades` (
  `id_raridade` INT NOT NULL,
  `tipo` VARCHAR(45) NULL,
  `drop` INT NULL,
  `id_item` INT NULL,
  `id_inimigo` INT NULL,
  PRIMARY KEY (`id_raridade`),
  INDEX `fk_raridades_Itens1_idx` (`id_item` ASC) ,
  INDEX `fk_raridades_inimigos1_idx` (`id_inimigo` ASC) ,
  CONSTRAINT `fk_raridades_Itens1`
    FOREIGN KEY (`id_item`)
    REFERENCES `rpg`.`Itens` (`id_item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_raridades_inimigos1`
    FOREIGN KEY (`id_inimigo`)
    REFERENCES `rpg`.`inimigos` (`id_inimigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rpg`.`inventarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rpg`.`inventarios` (
  `id_inventario` INT NOT NULL,
  `slot` VARCHAR(45) NULL,
  `refino` INT NULL,
  `id_personagem` INT NOT NULL,
  `id_item` INT NULL,
  PRIMARY KEY (`id_inventario`),
  INDEX `fk_iventarios_personagens1_idx` (`id_personagem` ASC) ,
  INDEX `fk_iventarios_Itens1_idx` (`id_item` ASC) ,
  CONSTRAINT `fk_iventarios_personagens1`
    FOREIGN KEY (`id_personagem`)
    REFERENCES `rpg`.`personagens` (`id_personagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_iventarios_Itens1`
    FOREIGN KEY (`id_item`)
    REFERENCES `rpg`.`Itens` (`id_item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
